### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by zhanhaibin** [rancher/rke#163]
**RKE version:**
   v0.0.8-dev
**Docker version: (`docker version`,`docker info` preferred)**
   Docker version 1.13.1, build 092cba3
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
   vmware 
**cluster.yml file:**

nodes:
  - address: 10.10.64.140
    user: ubuntu
    role: [controlplane, etcd]
    ssh_key_path: ~/.ssh/id_rsa
  - address: 10.10.64.141
    user: ubuntu
    role: [worker]
    ssh_key: |-
      -----BEGIN RSA PRIVATE KEY-----

      -----END RSA PRIVATE KEY-----

**Steps to Reproduce:**

**Results:**
ubuntu@master:/srv/k8s$ ./rke_linux-amd64 up --config cluster.yml
INFO[0000] Building Kubernetes cluster
INFO[0000] [ssh] Setup tunnel for host [10.10.64.140]
INFO[0000] [ssh] Setup tunnel for host [10.10.64.140]
INFO[0000] [ssh] Setup tunnel for host [10.10.64.141]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xefb683]

goroutine 32 [running]:
github.com/rancher/rke/vendor/golang.org/x/crypto/ssh.publicKeyCallback.auth(0xc4202b9260, 0xc4202b99a0, 0x20, 0x20, 0xc420479bb8, 0x6, 0x18688a0, 0xc420065600, 0x1859f60, 0xc420019620, ...)
        /go/src/github.com/rancher/rke/vendor/golang.org/x/crypto/ssh/client_auth.go:193 +0xb3
github.com/rancher/rke/vendor/golang.org/x/crypto/ssh.(*connection).clientAuthenticate(0xc4203ba780, 0xc42006e840, 0x0, 0xa)
        /go/src/github.com/rancher/rke/vendor/golang.org/x/crypto/ssh/client_auth.go:36 +0x369
github.com/rancher/rke/vendor/golang.org/x/crypto/ssh.(*connection).clientHandshake(0xc4203ba780, 0xc4202e8820, 0xf, 0xc42006e840, 0x0, 0x0)
        /go/src/github.com/rancher/rke/vendor/golang.org/x/crypto/ssh/client.go:112 +0x2e6
github.com/rancher/rke/vendor/golang.org/x/crypto/ssh.NewClientConn(0x18752c0, 0xc42043a1e0, 0xc4202e8820, 0xf, 0xc42006e780, 0x18752c0, 0xc42043a1e0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/rancher/rke/vendor/golang.org/x/crypto/ssh/client.go:82 +0xfa
github.com/rancher/rke/vendor/golang.org/x/crypto/ssh.Dial(0x118400c, 0x3, 0xc4202e8820, 0xf, 0xc42006e780, 0x0, 0x0, 0x2800c4202e8330)
        /go/src/github.com/rancher/rke/vendor/golang.org/x/crypto/ssh/client.go:176 +0xb3
github.com/rancher/rke/hosts.(*dialer).Dial(0xc4202b9160, 0x118400c, 0x3, 0xc4202b9220, 0x17, 0x40fe5c, 0x18fab00, 0xc420491a58, 0x0)
        /go/src/github.com/rancher/rke/hosts/dialer.go:39 +0x1b2
github.com/rancher/rke/hosts.(*dialer).Dial-fm(0x118400c, 0x3, 0xc4202b9220, 0x17, 0xc420491a58, 0x18fab00, 0xc420491a60, 0x6dc70d)
        /go/src/github.com/rancher/rke/hosts/dialer.go:66 +0x52
net/http.(*Transport).dial(0xc420284f00, 0x1871860, 0xc4200125e0, 0x118400c, 0x3, 0xc4202b9220, 0x17, 0x14cb93aed4e7f54, 0x531db31f938511ce, 0x93f34802f32d39a0, ...)
        /usr/local/go/src/net/http/transport.go:852 +0x7b
net/http.(*Transport).dialConn(0xc420284f00, 0x1871860, 0xc4200125e0, 0x0, 0x11845fb, 0x4, 0xc4202b9220, 0x17, 0x180001, 0x0, ...)
        /usr/local/go/src/net/http/transport.go:1008 +0x1c4c
net/http.(*Transport).getConn.func4(0xc420284f00, 0x1871860, 0xc4200125e0, 0xc42030a4b0, 0xc4203a7ec0)
        /usr/local/go/src/net/http/transport.go:908 +0x78
created by net/http.(*Transport).getConn
        /usr/local/go/src/net/http/transport.go:910 +0x3a3

**Comment by zhanhaibin** [comment]
ssh,已经可以免密登陆到node1机器
ubuntu@master:~/.ssh$ ssh ubuntu@10.10.64.141
Welcome to Ubuntu 16.04 LTS (GNU/Linux 4.4.0-21-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

588 packages can be updated.
281 updates are security updates.

Last login: Mon Dec 18 16:38:26 2017 from 10.10.64.140
ubuntu@node1:~$
