### ISSUE TITLE
rke up crashes with "panic: runtime error: invalid memory address or nil pointer dereference" when kube_config_cluster.yml from old cluster exists

### ISSUE THREAD

**Issue by dnoland1** [rancher/rke#1646]
**RKE version:**
```
$ rke -v
rke version v0.2.8
```
**Docker version: (`docker version`,`docker info` preferred)**
```
$ docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 1
Server Version: 18.09.8
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.138-rancher
Operating System: RancherOS v1.5.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.808GiB
Name: ip-10-0-0-10.us-west-2.compute.internal
ID: KMB5:FAMV:NCVA:IRYN:O3WO:ZU6R:AEFH:XNZI:ZDAN:3ILS:UYMM:D5TN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
$ uname -r
4.14.138-rancher
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**cluster.yml file:**
```yaml
authentication:
    sans:
      - "34.212.178.64"
nodes:

  - address: 34.212.178.64
    internal_address: 10.0.0.10
    user: rancher
    role: [controlplane,worker,etcd]


ssh_agent_auth: true

services:
  etcd:
    snapshot: true
    creation: 1h
    retention: 240h
```
**Steps to Reproduce:**
1. Copy a kube_config_cluster.yml from a cluster that no longer exists and put in working directory
2. run rke up

**Results:**
```
$ rke up
INFO[0000] Initiating Kubernetes cluster
INFO[0000] [state] Possible legacy cluster detected, trying to upgrade
INFO[0000] [reconcile] Rebuilding and updating local kube config
INFO[0000] Successfully Deployed local admin kubeconfig at [./kube_config_cluster.yml]
INFO[0000] [state] Fetching cluster state from Kubernetes
INFO[0030] Timed out waiting for kubernetes cluster to get state
WARN[0030] Failed to fetch state from kubernetes: Timeout waiting for kubernetes cluster to get state
INFO[0030] [dialer] Setup tunnel for host [34.212.178.64]
INFO[0030] [state] Fetching cluster state from Nodes
INFO[0030] [state] Pulling image [rancher/rke-tools:v0.1.42] on host [34.212.178.64]
INFO[0037] [state] Successfully pulled image [rancher/rke-tools:v0.1.42] on host [34.212.178.64]
INFO[0039] [state] Successfully started [cluster-state-deployer] container on host [34.212.178.64]
INFO[0040] [certificates] Getting Cluster certificates from Kubernetes
WARN[0040] Failed to fetch certs from kubernetes: Get https://34.212.178.64:6443/api/v1/namespaces/kube-system/secrets/kube-ca?timeout=30s: dial tcp 34.212.178.64:6443: connect: connection refused
INFO[0040] [certificates] Fetching kubernetes certificates from nodes
INFO[0041] [certificates] Successfully started [cert-fetcher] container on host [34.212.178.64]
INFO[0041] Successfully Deployed state file at [./cluster.rkestate]
INFO[0041] [certificates] Generating CA kubernetes certificates
INFO[0041] [certificates] Generating Kubernetes API server aggregation layer requestheader client CA certificates
INFO[0041] [certificates] Generating Node certificate
INFO[0042] [certificates] Generating etcd-10.0.0.10 certificate and key
INFO[0042] [certificates] Generating Kube Scheduler certificates
INFO[0042] [certificates] Generating Kube Proxy certificates
INFO[0042] [certificates] Generating Kubernetes API server proxy client certificates
INFO[0042] [certificates] Generating Kubernetes API server certificates
INFO[0042] [certificates] Generating Kube Controller certificates
INFO[0042] [certificates] Generating admin certificates and kubeconfig
INFO[0043] Successfully Deployed state file at [./cluster.rkestate]
INFO[0043] Building Kubernetes cluster
INFO[0043] [dialer] Setup tunnel for host [34.212.178.64]
INFO[0043] [network] No hosts added existing cluster, skipping port check
INFO[0043] [certificates] Deploying kubernetes certificates to Cluster nodes
INFO[0050] [reconcile] Rebuilding and updating local kube config
INFO[0050] Successfully Deployed local admin kubeconfig at [./kube_config_cluster.yml]
INFO[0050] [certificates] Successfully deployed kubernetes certificates to Cluster nodes
INFO[0050] [reconcile] Reconciling cluster state
INFO[0050] [reconcile] Check etcd hosts to be deleted
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1e48ecd]

goroutine 1 [running]:
github.com/rancher/rke/vendor/github.com/urfave/cli.HandleAction.func1(0xc0006a2d68)
	/private/tmp/rke-20190820-64776-1f3tqed/src/github.com/rancher/rke/vendor/github.com/urfave/cli/app.go:472 +0x287
panic(0x1ffe900, 0x3191610)
	/usr/local/Cellar/go/1.12.9/libexec/src/runtime/panic.go:522 +0x1b5
github.com/rancher/rke/vendor/k8s.io/client-go/util/cert.EncodeCertPEM(...)
	/private/tmp/rke-20190820-64776-1f3tqed/src/github.com/rancher/rke/vendor/k8s.io/client-go/util/cert/pem.go:69
github.com/rancher/rke/cluster.reconcileEtcd(0x24d8960, 0xc000040070, 0xc00019cd00, 0xc00019c400, 0xc00038c870, 0x0, 0x0)
	/private/tmp/rke-20190820-64776-1f3tqed/src/github.com/rancher/rke/cluster/reconcile.go:175 +0x13d
github.com/rancher/rke/cluster.ReconcileCluster(0x24d8960, 0xc000040070, 0xc00019c400, 0xc00019cd00, 0x0, 0x0, 0x21ce71f, 0xb, 0x0, 0x0, ...)
	/private/tmp/rke-20190820-64776-1f3tqed/src/github.com/rancher/rke/cluster/reconcile.go:43 +0x22a
github.com/rancher/rke/cmd.ClusterUp(0x24d8960, 0xc000040070, 0x0, 0x0, 0x0, 0x0, 0x0, 0x21ce71f, 0xb, 0x0, ...)
	/private/tmp/rke-20190820-64776-1f3tqed/src/github.com/rancher/rke/cmd/up.go:133 +0x650
github.com/rancher/rke/cmd.clusterUpFromCli(0xc000155540, 0x0, 0x0)
	/private/tmp/rke-20190820-64776-1f3tqed/src/github.com/rancher/rke/cmd/up.go:242 +0x60e
reflect.Value.call(0x1f93f20, 0x2278b50, 0x13, 0x21c6fa2, 0x4, 0xc0004fad08, 0x1, 0x1, 0xc000048080, 0x1014384, ...)
	/usr/local/Cellar/go/1.12.9/libexec/src/reflect/value.go:447 +0x461
reflect.Value.Call(0x1f93f20, 0x2278b50, 0x13, 0xc0004fad08, 0x1, 0x1, 0xc00030c8c8, 0x140, 0xc00030c8a0)
	/usr/local/Cellar/go/1.12.9/libexec/src/reflect/value.go:308 +0xa4
github.com/rancher/rke/vendor/github.com/urfave/cli.HandleAction(0x1f93f20, 0x2278b50, 0xc000155540, 0x0, 0x0)
	/private/tmp/rke-20190820-64776-1f3tqed/src/github.com/rancher/rke/vendor/github.com/urfave/cli/app.go:481 +0x1ff
github.com/rancher/rke/vendor/github.com/urfave/cli.Command.Run(0x21c6a04, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x21d8498, 0x14, 0x0, ...)
	/private/tmp/rke-20190820-64776-1f3tqed/src/github.com/rancher/rke/vendor/github.com/urfave/cli/command.go:186 +0x8d1
github.com/rancher/rke/vendor/github.com/urfave/cli.(*App).Run(0xc000001680, 0xc00000e060, 0x2, 0x2, 0x0, 0x0)
	/private/tmp/rke-20190820-64776-1f3tqed/src/github.com/rancher/rke/vendor/github.com/urfave/cli/app.go:235 +0x601
main.mainErr(0x24a3d20, 0xc000010010)
	/private/tmp/rke-20190820-64776-1f3tqed/src/github.com/rancher/rke/main.go:56 +0xf94
main.main()
	/private/tmp/rke-20190820-64776-1f3tqed/src/github.com/rancher/rke/main.go:19 +0x43
```
RKE should handle this more gracefully.

**Comment by dnoland1** [comment]
Looks like this is already fixed in v0.3.0 according to @superseb . Closing...
