### ISSUE TITLE
rke 1.17.6 etcd error   etcdserver: create wal error: unlinkat /var/lib/rancher/etcd/member/wal: device or resource busy

### ISSUE THREAD

**Issue by sunhuaxu** [rancher/rke#2221]
**RKE version:**
rke version v1.1.2

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 19.03.8, build afacb8b

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.5"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.5 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.5:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.5"

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
DO

**cluster.yml file:**
nodes:
  - address: 192.168.101.104
    hostname_override: master01
    internal_address:
    user: jzgkfx
    role:
      - controlplane
      - etcd
    ssh_key_path: /home/jzgkfx/.ssh/id_rsa
    port: 22
  - address: 192.168.101.105
    hostname_override: worker01
    internal_address:
    user: jzgkfx
    role:
      - worker
      - etcd
    ssh_key_path: /home/jzgkfx/.ssh/id_rsa
    port: 22
  - address: 192.168.101.106
    hostname_override: worker02
    internal_address:
    labels:
      app: ingress
    user: jzgkfx
    role:
      - worker
      - etcd
    ssh_key_path: /home/jzgkfx/.ssh/id_rsa
    port: 22

ssh_key_path: ~/.ssh/id_rsa
ssh_cert_path: ""
ssh_agent_auth: false

ignore_docker_version: false
docker_root_dir: "/data/k8s/docker"

kubernetes_version: 
system_images:
  etcd: rancher/coreos-etcd:v3.4.3-rancher1
  alpine: rancher/rke-tools:v0.1.56
  nginx_proxy: rancher/rke-tools:v0.1.56
  cert_downloader: rancher/rke-tools:v0.1.56
  kubernetes_services_sidecar: rancher/rke-tools:v0.1.56
  kubedns: rancher/k8s-dns-kube-dns:1.15.0
  dnsmasq: rancher/k8s-dns-dnsmasq-nanny:1.15.0
  kubedns_sidecar: rancher/k8s-dns-sidecar:1.15.0
  kubedns_autoscaler: rancher/cluster-proportional-autoscaler:1.7.1
  coredns: rancher/coredns-coredns:1.6.5
  coredns_autoscaler: rancher/cluster-proportional-autoscaler:1.7.1
  nodelocal: rancher/k8s-dns-node-cache:1.15.7
  kubernetes: rancher/hyperkube:v1.17.6-rancher2
  flannel: rancher/coreos-flannel:v0.11.0-rancher1
  flannel_cni: rancher/flannel-cni:v0.3.0-rancher6
  calico_node: rancher/calico-node:v3.13.4
  calico_cni: rancher/calico-cni:v3.13.4
  calico_controllers: rancher/calico-kube-controllers:v3.13.4
  calico_ctl: rancher/calico-ctl:v3.13.4
  calico_flexvol: rancher/calico-pod2daemon-flexvol:v3.13.4
  canal_node: rancher/calico-node:v3.13.4
  canal_cni: rancher/calico-cni:v3.13.4
  canal_flannel: rancher/coreos-flannel:v0.11.0
  canal_flexvol: rancher/calico-pod2daemon-flexvol:v3.13.4
  pod_infra_container: rancher/pause:3.1
  ingress: rancher/nginx-ingress-controller:nginx-0.32.0-rancher1
  ingress_backend: rancher/nginx-ingress-controller-defaultbackend:1.5-rancher1
  metrics_server: rancher/metrics-server:v0.3.6
  windows_pod_infra_container: rancher/kubelet-pause:v0.1.3
  weave_node: weaveworks/weave-kube:2.6.4
  weave_cni: weaveworks/weave-npc:2.6.4

services:
  etcd:
    snapshot: true
    creation: 5m0s
    retention: 24h
    backup_config:
      enabled: true
      interval_hours: 12
      retention: 6
    extra_env: []
    extra_args:
      auto-compaction-mode: periodic
      auto-compaction-retention: 60m
      quota-backend-bytes: 6442450944
      snapshot-count: 50000
    extra_binds:
      - "/data/k8s/etcd/snap:/var/lib/rancher/etcd/member/snap"
      - "/data/k8s/etcd/wal:/var/lib/rancher/etcd/member/wal"
      - "/etc/localtime:/etc/localtime"

  kube-api:
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: 20000-40000
    pod_security_policy: false
    extra_args:
      watch-cache: true
      default-watch-cache-size: 1500
      event-ttl: 1h0m0s
      max-requests-inflight: 800
      max-mutating-requests-inflight: 400
      kubelet-timeout: 5s
      audit-log-path: "-"
      delete-collection-workers: 3
      v: 4
    extra_binds:
      - "/etc/localtime:/etc/localtime"

**Steps to Reproduce:**
WARN[0058] [etcd] host [192.168.101.104] failed to check etcd health: failed to get /health for host [192.168.101.104]: Get https://192.168.101.104:2379/health: Unable to access the service on 192.168.101.104:2379. The service might be still starting up. Error: ssh: rejected: connect failed (Connection refused) 
WARN[0073] [etcd] host [192.168.101.105] failed to check etcd health: failed to get /health for host [192.168.101.105]: Get https://192.168.101.105:2379/health: Unable to access the service on 192.168.101.105:2379. The service might be still starting up. Error: ssh: rejected: connect failed (Connection refused) 
WARN[0089] [etcd] host [192.168.101.106] failed to check etcd health: failed to get /health for host [192.168.101.106]: Get https://192.168.101.106:2379/health: Unable to access the service on 192.168.101.106:2379. The service might be still starting up. Error: ssh: rejected: connect failed (Connection refused) 
FATA[0089] [etcd] Failed to bring up Etcd Plane: etcd cluster is unhealthy: hosts [192.168.101.104,192.168.101.105,192.168.101.106] failed to report healthy. Check etcd container logs on each host for more information 

**Results:**
docker logs etcd

2020-08-27 16:25:55.905714 W | pkg/flags: unrecognized environment variable ETCD_UNSUPPORTED_ARCH=x86_64
[WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
2020-08-27 16:25:55.905847 I | etcdmain: etcd Version: 3.4.3
2020-08-27 16:25:55.905853 I | etcdmain: Git SHA: 3cf2f69b5
2020-08-27 16:25:55.905857 I | etcdmain: Go Version: go1.12.12
2020-08-27 16:25:55.905861 I | etcdmain: Go OS/Arch: linux/amd64
2020-08-27 16:25:55.905871 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
2020-08-27 16:25:55.905974 N | etcdmain: the server is already initialized as member before, starting as etcd member...
[WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
2020-08-27 16:25:55.906041 I | embed: peerTLS: cert = /etc/kubernetes/ssl/kube-etcd-192.168.101.104.pem, key = /etc/kubernetes/ssl/kube-etcd-192.168.101.104-key.pem, trusted-ca = /etc/kubernetes/ssl/kube-ca.pem, client-cert-auth = true, crl-file = 
2020-08-27 16:25:55.907315 I | embed: name = etcd-master01
2020-08-27 16:25:55.907329 I | embed: data dir = /var/lib/rancher/etcd/
2020-08-27 16:25:55.907334 I | embed: member dir = /var/lib/rancher/etcd/member
2020-08-27 16:25:55.907339 I | embed: heartbeat = 500ms
2020-08-27 16:25:55.907343 I | embed: election = 5000ms
2020-08-27 16:25:55.907347 I | embed: snapshot count = 50000
2020-08-27 16:25:55.907358 I | embed: advertise client URLs = https://192.168.101.104:2379,https://192.168.101.104:4001
2020-08-27 16:25:55.921489 C | etcdserver: create wal error: unlinkat /var/lib/rancher/etcd/member/wal: device or resource busy
panic: create wal error: unlinkat /var/lib/rancher/etcd/member/wal: device or resource busy

goroutine 1 [running]:
github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc00000d560, 0x1091342, 0x14, 0xc0002e6508, 0x1, 0x1)
        /home/ec2-user/go/pkg/mod/github.com/coreos/pkg@v0.0.0-20160727233714-3ac0863d7acf/capnslog/pkg_logger.go:75 +0x135
go.etcd.io/etcd/etcdserver.startNode(0x7ffda86d4e77, 0xd, 0x0, 0x0, 0x0, 0x0, 0xc000288600, 0x2, 0x2, 0xc000263300, ...)
        /tmp/etcd-release-3.4.3/etcd/release/etcd/etcdserver/raft.go:438 +0xf1c
go.etcd.io/etcd/etcdserver.NewServer(0x7ffda86d4e77, 0xd, 0x0, 0x0, 0x0, 0x0, 0xc000288600, 0x2, 0x2, 0xc000263300, ...)
        /tmp/etcd-release-3.4.3/etcd/release/etcd/etcdserver/server.go:407 +0x4950
go.etcd.io/etcd/embed.StartEtcd(0xc0002ae000, 0xc0002ae580, 0x0, 0x0)
        /tmp/etcd-release-3.4.3/etcd/release/etcd/embed/etcd.go:211 +0x9d0
go.etcd.io/etcd/etcdmain.startEtcd(0xc0002ae000, 0x108423e, 0x6, 0x1, 0xc00024d1d0)
        /tmp/etcd-release-3.4.3/etcd/release/etcd/etcdmain/etcd.go:302 +0x40
go.etcd.io/etcd/etcdmain.startEtcdOrProxyV2()
        /tmp/etcd-release-3.4.3/etcd/release/etcd/etcdmain/etcd.go:144 +0x2f71
go.etcd.io/etcd/etcdmain.Main()
        /tmp/etcd-release-3.4.3/etcd/release/etcd/etcdmain/main.go:46 +0x38
main.main()
        /tmp/etcd-release-3.4.3/etcd/release/etcd/main.go:28 +0x20
2020-08-27 16:26:02.636992 W | pkg/flags: unrecognized environment variable ETCD_UNSUPPORTED_ARCH=x86_64
[WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
2020-08-27 16:26:02.637134 I | etcdmain: etcd Version: 3.4.3
2020-08-27 16:26:02.637145 I | etcdmain: Git SHA: 3cf2f69b5
2020-08-27 16:26:02.637149 I | etcdmain: Go Version: go1.12.12
2020-08-27 16:26:02.637153 I | etcdmain: Go OS/Arch: linux/amd64
2020-08-27 16:26:02.637162 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
2020-08-27 16:26:02.637278 N | etcdmain: the server is already initialized as member before, starting as etcd member...
[WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
2020-08-27 16:26:02.637329 I | embed: peerTLS: cert = /etc/kubernetes/ssl/kube-etcd-192.168.101.104.pem, key = /etc/kubernetes/ssl/kube-etcd-192.168.101.104-key.pem, trusted-ca = /etc/kubernetes/ssl/kube-ca.pem, client-cert-auth = true, crl-file = 
2020-08-27 16:26:02.638450 I | embed: name = etcd-master01
2020-08-27 16:26:02.638468 I | embed: data dir = /var/lib/rancher/etcd/
2020-08-27 16:26:02.638478 I | embed: member dir = /var/lib/rancher/etcd/member
2020-08-27 16:26:02.638483 I | embed: heartbeat = 500ms
2020-08-27 16:26:02.638487 I | embed: election = 5000ms
2020-08-27 16:26:02.638491 I | embed: snapshot count = 50000
2020-08-27 16:26:02.638514 I | embed: advertise client URLs = https://192.168.101.104:2379,https://192.168.101.104:4001
2020-08-27 16:26:02.645499 C | etcdserver: create wal error: unlinkat /var/lib/rancher/etcd/member/wal: device or resource busy
panic: create wal error: unlinkat /var/lib/rancher/etcd/member/wal: device or resource busy

**Comment by sunhuaxu** [comment]
Modify the etcd configuration，install sucess.

services:
etcd:
snapshot: true
creation: 5m0s
retention: 24h
backup_config:
enabled: true
interval_hours: 12
retention: 6
extra_env: []
extra_args:
auto-compaction-mode: periodic
auto-compaction-retention: 60m
quota-backend-bytes: 6442450944
snapshot-count: 50000
extra_binds:
- "/data/k8s/etcd:/var/lib/rancher/etcd/member"
- "/etc/localtime:/etc/localtime"
