### ISSUE TITLE
Panic - runtime error when master node is removed from the Kubernetes cluster

### ISSUE THREAD

**Issue by soumyalj** [rancher/rke#24]
rke version v0.0.2-dev

Steps:
1. Create a cluster with one master [controlplane, etcd] node and the other worker node using cluster.yml file.  Use the command ```./rke_darwin-amd64 cluster up --cluster-file cluster.yml ```
Cluster.yml file example:
```
auth:
  strategy: x509
network:
  plugin: flannel
hosts:
  - advertised_hostname: server1
    ip: 1.1.1.1
    user: ubuntu
    role: [controlplane, etcd]
    docker_socket: /var/run/docker.sock
    advertise_address: 10.1.1.1
  - advertised_hostname: server2
    ip: 2.2.2.2
    user: ubuntu
    role: [worker]
    advertise_address: 10.2.2.2

services:
  etcd:
    image: quay.io/coreos/etcd:latest
  kube-api:
    image: quay.io/coreos/hyperkube:v1.7.5_coreos.0
    service_cluster_ip_range: 10.233.0.0/18
    extra_args:
      v: 4
  kube-controller:
    image: quay.io/coreos/hyperkube:v1.7.5_coreos.0
    cluster_cidr: 10.233.64.0/18
    service_cluster_ip_range: 10.233.0.0/18
  scheduler:
    image: quay.io/coreos/hyperkube:v1.7.5_coreos.0
  kubelet:
    image: quay.io/coreos/hyperkube:v1.7.5_coreos.0
    cluster_domain: cluster.local
    cluster_dns_server: 10.233.0.3
    infra_container_image: gcr.io/google_containers/pause-amd64:3.0
  kubeproxy:
    image: quay.io/coreos/hyperkube:v1.7.5_coreos.0

```

2. Remove the master node in the cluster.yml file and rerun the ```./rke_darwin-amd64 cluster up``` command
It fails with a panic as below
```
soumyas-MBP:rke soumya$ ./rke_darwin-amd64 cluster up --cluster-file cluster.yml 
INFO[0000] Building Kubernetes cluster                  
INFO[0000] [ssh] Checking private key                   
INFO[0000] [ssh] Start tunnel for host [soumyarketes2]  
INFO[0000] [state] Fetching cluster state from Kubernetes 
INFO[0000] [state] Successfully Fetched cluster state to Kubernetes ConfigMap: cluster-state 
INFO[0000] [certificates] Getting Cluster certificates from Kubernetes 
INFO[0000] [certificates] Successfully fetched Cluster certificates from Kubernetes 
INFO[0000] [certificates] Deploying kubernetes certificates to Cluster nodes 
INFO[0008] [certificates] Successfully deployed kubernetes certificates to Cluster nodes 
INFO[0008] [etcd] Building up Etcd Plane..              
INFO[0008] [etcd] Successfully started Etcd Plane..     
INFO[0008] [controlplane] Building up Controller Plane.. 
INFO[0008] [controlplane] Successfully started Controller Plane.. 
INFO[0008] [worker] Building up Worker Plane..          
INFO[0008] [worker] Container nginx-proxy is already running on host [soumyarketes2] 
INFO[0008] [worker] Container kubelet is already running on host [soumyarketes2] 
INFO[0008] [worker] Container kube-proxy is already running on host [soumyarketes2] 
INFO[0008] [worker] Successfully started Worker Plane.. 
INFO[0008] [reconcile] Reconciling cluster state        
INFO[0008] [reconcile] Rebuilding and update local kube config 
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 1 [running]:
github.com/rancher/rke/vendor/github.com/urfave/cli.HandleAction.func1(0xc42057c900)
	/go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/app.go:472 +0x28d
panic(0x1c499e0, 0x24b7800)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/rancher/rke/cluster.rebuildLocalAdminConfig(0xc4201d0000, 0x25, 0x0)
	/go/src/github.com/rancher/rke/cluster/cluster.go:165 +0x54a
github.com/rancher/rke/cluster.ReconcileCluster(0xc4201d0000, 0xc4204dc240, 0x0, 0x0)
	/go/src/github.com/rancher/rke/cluster/cluster.go:127 +0xa3
github.com/rancher/rke/cmd.ClusterUp(0xc420114480, 0x43a, 0x43a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rke/cmd/cluster.go:94 +0x17d
github.com/rancher/rke/cmd.clusterUpFromCli(0xc420224000, 0x0, 0x0)
	/go/src/github.com/rancher/rke/cmd/cluster.go:133 +0xdd
reflect.Value.call(0x1c07de0, 0x1dee640, 0x13, 0x1d78844, 0x4, 0xc4205828a0, 0x1, 0x1, 0xc420582828, 0x1d53f40, ...)
	/usr/local/go/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0x1c07de0, 0x1dee640, 0x13, 0xc4205828a0, 0x1, 0x1, 0x140, 0xc420224000, 0x0)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/rancher/rke/vendor/github.com/urfave/cli.HandleAction(0x1c07de0, 0x1dee640, 0xc420224000, 0x0, 0x0)
	/go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/app.go:481 +0x198
github.com/rancher/rke/vendor/github.com/urfave/cli.Command.Run(0x1d780aa, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1d85712, 0x14, 0x0, ...)
	/go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/command.go:186 +0xab8
github.com/rancher/rke/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc4202d4180, 0xc4201e5cc0, 0x0, 0x0)
	/go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/app.go:355 +0xa1f
github.com/rancher/rke/vendor/github.com/urfave/cli.Command.startApp(0x1d7a704, 0x7, 0x1d7a704, 0x7, 0x0, 0x0, 0x0, 0x1d8a255, 0x19, 0x0, ...)
	/go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/command.go:273 +0x81b
github.com/rancher/rke/vendor/github.com/urfave/cli.Command.Run(0x1d7a704, 0x7, 0x1d7a704, 0x7, 0x0, 0x0, 0x0, 0x1d8a255, 0x19, 0x0, ...)
	/go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/command.go:74 +0x142c
github.com/rancher/rke/vendor/github.com/urfave/cli.(*App).Run(0xc4202d4000, 0xc42000e140, 0x5, 0x5, 0x0, 0x0)
	/go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/app.go:235 +0x5d6
main.mainErr(0xc4202445a0, 0xc420583f68)
	/go/src/github.com/rancher/rke/main.go:41 +0x2f8
main.main()
	/go/src/github.com/rancher/rke/main.go:14 +0x22

```

**Comment by soumyalj** [comment]
Tested with rke version v0.0.4-dev. Created a cluster with one master and one worker node using cluster.yml file,
Removed the master node from the cluster.yml file and cluster up command was run again. 
There was no panic runtime error. A relevant error message was displayed as below
```
soumya$ ./rke_darwin-amd64 cluster up --cluster-file cluster.yml
INFO[0000] Building Kubernetes cluster                  
FATA[0000] Failed to validate cluster: Cluster must have at least one control plane host 

```
