### ISSUE TITLE
Adding options to kubelet (cpu_manager_policy)

### ISSUE THREAD

**Issue by linecolumn** [rancher/rke#2463]
There is no way to add other ("non predefined") options to kubelet trough cluster.yml, or I do not see possibility.

My use case scenario is to add Control CPU Management Policies (--cpu_manager_policy="static").

**RKE version:**

RKE v1.2.6rc4

**Comment by superseb** [comment]
`extra_args` can be used to specify additional parameters as shown on https://rancher.com/docs/rke/latest/en/config-options/services/services-extras/. Is this sufficient or do you need more configuration methods for this to work?

**Comment by linecolumn** [comment]
I've tried with `    cpu-manager-policy: 'static'` under `extra_args`, but `rke up` was not finishing trough, was getting:


```
DEBU[0093] [healthcheck] Failed to check http://localhost:10248/healthz for service [kubelet] on host [master1]: Get "http://localhost:10248/healthz": Unable to access the service on localhost:10248. The service might be still starting up. Error: ssh: rejected: connect failed (Connection refused), try #1 
[...]
ERRO[0157] Failed to upgrade worker components on NotReady hosts, error: [Failed to verify healthcheck: Failed to check http://localhost:10248/healthz for service [kubelet] on host [master1]: Get "http://localhost:10248/healthz": Unable to access the service on localhost:10248. The service might be still starting up. Error: ssh: rejected: connect failed (Connection refused), log: 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record/event.go:299 +0x6e] 
```

Am I missing how to utilize `extra_args` in this case (changing policy for cpu_manager)?

**Comment by superseb** [comment]
The requirements are stated on https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/#static-policy, please share the full `cluster.yml` with what you configured to check. The output of `docker logs kubelet` on the node would also be helpful.

**Comment by linecolumn** [comment]
It seems I would need to remove `/var/lib/kubelet/cpu_manager_state` before applying changes to the cluster (or to re-create it). Thanks! 

```
    extra_args:
      cpu-manager-policy: 'static'
      kube-reserved: 'cpu=500m'
```

```
E0215 15:08:06.547309 1966416 cpu_manager.go:203] [cpumanager] could not initialize checkpoint manager: could not restore state from checkpoint: configured policy "static" differs from state checkpoint policy "none", please drain this node and delete the CPU manager checkpoint file "/var/lib/kubelet/cpu_manager_state" before restarting Kubelet, please drain node and remove policy state file
F0215 15:08:06.547322 1966416 kubelet.go:1350] Failed to start ContainerManager start cpu manager error: could not restore state from checkpoint: configured policy "static" differs from state checkpoint policy "none", please drain this node and delete the CPU manager checkpoint file "/var/lib/kubelet/cpu_manager_state" before restarting Kubelet
goroutine 1189 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc000010001, 0xc001d74c00, 0x15b, 0x1e1)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x70d14c0, 0xc000000003, 0x0, 0x0, 0xc001120380, 0x6f3cf1a, 0xa, 0x546, 0x0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:975 +0x19b
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printf(0x70d14c0, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x4935d79, 0x23, 0xc001c16be0, 0x1, ...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:750 +0x191
k8s.io/kubernetes/vendor/k8s.io/klog/v2.Fatalf(...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1502
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).initializeRuntimeDependentModules(0xc001098a80)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1350 +0x446
sync.(*Once).doSlow(0xc0010992c8, 0xc000945de8)
	/usr/local/go/src/sync/once.go:66 +0xec
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:57
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).updateRuntimeUp(0xc001098a80)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:2179 +0x672
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc001c17760)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001c17760, 0x4f11e00, 0xc000b9a060, 0x1, 0xc0002780c0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001c17760, 0x12a05f200, 0x0, 0x1, 0xc0002780c0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc001c17760, 0x12a05f200, 0xc0002780c0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by k8s.io/kubernetes/pkg/kubelet.(*Kubelet).Run
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1403 +0x16a
```
