### ISSUE TITLE
etcd snapshot-save panics on minimal `cluster.yml`

### ISSUE THREAD

**Issue by superseb** [rancher/rke#3099]
**RKE version:**
v1.4.0

**Docker version: (`docker version`,`docker info` preferred)**
20.10.21

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 20.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**cluster.yml file:**
```
nodes:
- address: x
  internal_address: y
  user: ubuntu
  role: [controlplane,worker,etcd]
  ssh_key_path: ~/.ssh/id_rsa
- address: x
  internal_address: y
  user: ubuntu
  role: [controlplane,worker,etcd]
  ssh_key_path: ~/.ssh/id_rsa
- address: x
  internal_address: y
  user: ubuntu
  role: [controlplane,worker,etcd]
  ssh_key_path: ~/.ssh/id_rsa
ssh_agent_auth: true
```

**Steps to Reproduce:**
1. Run `rke up`
2. Run `rke etcd snapshot-save`

**Results:**
```
INFO[0017] Container [etcd-snapshot-once] is still running on host [34.219.223.23]: stderr: [time="2022-11-18T18:53:38Z" level=info msg="Created local backup" name="rke_etcd_snapshot_2022-11-18T19:53:21+01:00" runtime=122.450195ms
], stdout: []                  
INFO[0018] Removing container [etcd-snapshot-once] on host [34.219.223.23], try #1 
INFO[0019] [etcd] Running snapshot save once on host [54.212.140.184] 
INFO[0019] Finding container [etcd] on host [54.212.140.184], try #1 
INFO[0019] Image [rancher/rke-tools:v0.1.87] exists on host [54.212.140.184] 
INFO[0020] Starting container [etcd-snapshot-once] on host [54.212.140.184], try #1 
INFO[0020] [etcd] Successfully started [etcd-snapshot-once] container on host [54.212.140.184] 
INFO[0020] Waiting for [etcd-snapshot-once] container to exit on host [54.212.140.184] 
INFO[0021] Container [etcd-snapshot-once] is still running on host [54.212.140.184]: stderr: [time="2022-11-18T18:53:42Z" level=info msg="Created local backup" name="rke_etcd_snapshot_2022-11-18T19:53:21+01:00" runtime=125.202242ms
], stdout: []           
INFO[0022] Removing container [etcd-snapshot-once] on host [54.212.140.184], try #1 
INFO[0022] [etcd] Finished saving snapshot [rke_etcd_snapshot_2022-11-18T19:53:21+01:00] on all etcd hosts 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2580755]
                                                                                                                                                               
goroutine 1 [running]:
github.com/rancher/rke/cluster.(*Cluster).SnapshotEtcd(0xc000a56000, {0x2e15b18, 0xc0000520a0}, {0xc0003c9380, 0x2b})
        /go/src/github.com/rancher/rke/cluster/etcd.go:54 +0x415               
github.com/rancher/rke/cmd.SnapshotSaveEtcdHosts({0x2e15b18, 0xc0000520a0}, 0x0, {0x0, 0x0, 0x0}, {{0x0, 0x0}, {0x7ff7bfeff798, 0xe}, ...}, ...)
        /go/src/github.com/rancher/rke/cmd/etcd.go:133 +0x226
github.com/rancher/rke/cmd.SnapshotSaveEtcdHostsFromCli(0xc0002fa000)                                                                                          
        /go/src/github.com/rancher/rke/cmd/etcd.go:321 +0x333
github.com/urfave/cli.HandleAction({0x2731b00, 0x2b8d208}, 0xd)     
        /go/pkg/mod/github.com/urfave/cli@v1.22.2/app.go:523 +0xa8  
github.com/urfave/cli.Command.Run({{0x2a9d1c5, 0xd}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x2abe9f7, 0x1f}, {0x0, ...}, ...}, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.22.2/command.go:174 +0x63a
github.com/urfave/cli.(*App).RunAsSubcommand(0xc000142a80, 0xc000201ce0)
        /go/pkg/mod/github.com/urfave/cli@v1.22.2/app.go:404 +0x9ec
github.com/urfave/cli.Command.startApp({{0x2a8c2ae, 0x4}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x2af8afc, 0x34}, {0x0, ...}, ...}, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.22.2/command.go:373 +0x6e9
github.com/urfave/cli.Command.Run({{0x2a8c2ae, 0x4}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x2af8afc, 0x34}, {0x0, ...}, ...}, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.22.2/command.go:102 +0x825
github.com/urfave/cli.(*App).Run(0xc0001428c0, {0xc00004c0a0, 0x5, 0x5})       
        /go/pkg/mod/github.com/urfave/cli@v1.22.2/app.go:276 +0x80c
main.mainErr()                                    
        /go/src/github.com/rancher/rke/main.go:81 +0x1825
main.main()                                                                    
        /go/src/github.com/rancher/rke/main.go:25 +0x33
```

Workaround: add minimal config to `cluster.yml`:

```
services:
  etcd:
    backup_config:
      interval_hours: 12
      retention: 6
```

**Comment by jiaqiluo** [comment]
### Root cause
backend tries to access a field that is nil, which causes panic. 
  
### What was fixed, or what changes have occurred
  
Add a check before accessing the field

### Areas or cases that should be tested
 
The test case will be exact the same as the issue provides. 

### What areas could experience regressions?
  no
### Are the repro steps accurate/minimal?
yes

**Comment by jiaqiluo** [comment]
can be validated in RKE CLI v1.4.3-rc1
