### ISSUE TITLE
Better error message for invalid ssh_key_path value

### ISSUE THREAD

**Issue by Overv** [rancher/rke#347]
**RKE version:**

rke version v0.0.8-dev

**Docker version: (`docker version`,`docker info` preferred)**

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

VirtualBox

**cluster.yml file:**

```
nodes:
  - address: 172.30.1.5
    user: vagrant
    role: [controlplane,worker,etcd]

ssh_key_path: some/invalid/path
```

**Steps to Reproduce:**

Try to start a cluster with an invalid SSH key path in the cluster configuration file.

**Results:**

Crash:

```
INFO[0000] [ssh] Setup tunnel for host [172.30.1.5]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xf032a3]

goroutine 38 [running]:
github.com/rancher/rke/vendor/golang.org/x/crypto/ssh.publicKeyCallback.auth(0xc420187d40, 0xc420226200, 0x20, 0x20, 0xc42027da38, 0x7, 0x187abc0, 0xc42001dce0, 0x186c200, 0xc420015620, ...)
        /home/overv/gostuff/src/github.com/rancher/rke/vendor/golang.org/x/crypto/ssh/client_auth.go:193 +0xb3
github.com/rancher/rke/vendor/golang.org/x/crypto/ssh.(*connection).clientAuthenticate(0xc420291180, 0xc4200a46c0, 0x0, 0xa)
        /home/overv/gostuff/src/github.com/rancher/rke/vendor/golang.org/x/crypto/ssh/client_auth.go:36 +0x369
github.com/rancher/rke/vendor/golang.org/x/crypto/ssh.(*connection).clientHandshake(0xc420291180, 0xc420262b00, 0xd, 0xc4200a46c0, 0x0, 0x0)
        /home/overv/gostuff/src/github.com/rancher/rke/vendor/golang.org/x/crypto/ssh/client.go:112 +0x2e6
github.com/rancher/rke/vendor/golang.org/x/crypto/ssh.NewClientConn(0x18875e0, 0xc42000e460, 0xc420262b00, 0xd, 0xc4200a4600, 0x18875e0, 0xc42000e460, 0x0, 0x0, 0x0, ...)
        /home/overv/gostuff/src/github.com/rancher/rke/vendor/golang.org/x/crypto/ssh/client.go:82 +0xfa
github.com/rancher/rke/vendor/golang.org/x/crypto/ssh.Dial(0x118dd2c, 0x3, 0xc420262b00, 0xd, 0xc4200a4600, 0x0, 0x0, 0x0)
        /home/overv/gostuff/src/github.com/rancher/rke/vendor/golang.org/x/crypto/ssh/client.go:176 +0xb3
github.com/rancher/rke/hosts.(*dialer).Dial(0xc420187c00, 0x118dd2c, 0x3, 0xc420187ce0, 0x17, 0x41181c, 0x190ce80, 0xc420051a58, 0x0)
        /home/overv/gostuff/src/github.com/rancher/rke/hosts/dialer.go:39 +0x1b2
github.com/rancher/rke/hosts.(*dialer).Dial-fm(0x118dd2c, 0x3, 0xc420187ce0, 0x17, 0xc420051a58, 0x190ce80, 0xc420051a60, 0x6e2add)
        /home/overv/gostuff/src/github.com/rancher/rke/hosts/dialer.go:66 +0x52
net/http.(*Transport).dial(0xc420204a50, 0x1883b80, 0xc4200165f0, 0x118dd2c, 0x3, 0xc420187ce0, 0x17, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/http/transport.go:852 +0x7b
net/http.(*Transport).dialConn(0xc420204a50, 0x1883b80, 0xc4200165f0, 0x0, 0x118e317, 0x4, 0xc420187ce0, 0x17, 0x0, 0x0, ...)
        /usr/local/go/src/net/http/transport.go:1008 +0x1c4c
net/http.(*Transport).getConn.func4(0xc420204a50, 0x1883b80, 0xc4200165f0, 0xc4203809c0, 0xc4203f6ea0)
        /usr/local/go/src/net/http/transport.go:908 +0x78
created by net/http.(*Transport).getConn
        /usr/local/go/src/net/http/transport.go:910 +0x3a3
```

There should be a more user friendly message than this in case the SSH key path is incorrect. It took me 20 minutes to figure out what was wrong.

**Comment by moelsayed** [comment]
@Overv that's an old rke version. Please try the latest.

**Comment by Overv** [comment]
Confirmed fixed in newer versions.
