### ISSUE TITLE
segmentation violation when doing `rke up`

### ISSUE THREAD

**Issue by jazoom** [rancher/rke#841]
After the issues with Ubuntu 18.04 yesterday I decided to check out RKE by using Debian 9.5. This time, there's another issue preventing installation.

Even though I couldn't find anything in your docs about minimum RAM requirements, [this dude](https://hackernoon.com/deploying-kubernetes-on-premise-with-rke-and-deploying-openfaas-on-it-part-1-69a35ddfa507) seemed to have no trouble with 1GB. Anyway, I increased the RAM to 4GB for each node and the issue persisted. I used `rke remove` and tried again about 5 times in total. Always a similar result.

**RKE version:** v0.1.8

**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:31:19 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:31:19 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Vultr

**cluster.yml file:**
```
nodes:
  - hostname_override: kube1
    address: *address*
    port: *address*
    user: root
    internal_address: *address*
    role:
      - controlplane
      - etcd
    docker_socket: /var/run/docker.sock
    ssh_key: ""
    ssh_key_path: ""
    labels: {}
  - hostname_override: kube2
    address: *address*
    port: *address*
    user: root
    internal_address: *address*
    role:
      - controlplane
      - etcd
      - worker
    docker_socket: /var/run/docker.sock
    ssh_key: ""
    ssh_key_path: ""
    labels: {}
  - hostname_override: kube3
    address: *address*
    port: *address*
    user: root
    internal_address: *address*
    role:
      - controlplane
      - etcd
      - worker
    docker_socket: /var/run/docker.sock
    ssh_key: ""
    ssh_key_path: ""
    labels: {}
  - hostname_override: kube4
    address: *address*
    port: *address*
    user: root
    internal_address: *address*
    role:
      - worker
    docker_socket: /var/run/docker.sock
    ssh_key: ""
    ssh_key_path: ""
    labels: {}
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    snapshot: false
    retention: ""
    creation: ""
  kube-api:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: ""
    pod_security_policy: false
  kube-controller:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
  kubelet:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_domain: cluster.local
    infra_container_image: ""
    cluster_dns_server: 10.43.0.10
    fail_swap_on: true
  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
network:
  plugin: canal
  options: {}
authentication:
  strategy: x509
  options: {}
  sans: []
addons: ""
addons_include: []
system_images:
  etcd: rancher/coreos-etcd:v3.1.12
  alpine: rancher/rke-tools:v0.1.10
  nginx_proxy: rancher/rke-tools:v0.1.10
  cert_downloader: rancher/rke-tools:v0.1.10
  kubernetes_services_sidecar: rancher/rke-tools:v0.1.10
  kubedns: rancher/k8s-dns-kube-dns-amd64:1.14.8
  dnsmasq: rancher/k8s-dns-dnsmasq-nanny-amd64:1.14.8
  kubedns_sidecar: rancher/k8s-dns-sidecar-amd64:1.14.8
  kubedns_autoscaler: rancher/cluster-proportional-autoscaler-amd64:1.0.0
  kubernetes: rancher/hyperkube:v1.10.5-rancher1
  flannel: rancher/coreos-flannel:v0.9.1
  flannel_cni: rancher/coreos-flannel-cni:v0.2.0
  calico_node: rancher/calico-node:v3.1.1
  calico_cni: rancher/calico-cni:v3.1.1
  calico_controllers: ""
  calico_ctl: rancher/calico-ctl:v2.0.0
  canal_node: rancher/calico-node:v3.1.1
  canal_cni: rancher/calico-cni:v3.1.1
  canal_flannel: rancher/coreos-flannel:v0.9.1
  wave_node: weaveworks/weave-kube:2.1.2
  weave_cni: weaveworks/weave-npc:2.1.2
  pod_infra_container: rancher/pause-amd64:3.1
  ingress: rancher/nginx-ingress-controller:0.10.2-rancher3
  ingress_backend: rancher/nginx-ingress-controller-defaultbackend:1.4
ssh_key_path: *path*
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
ignore_docker_version: false
kubernetes_version: ""
private_registries: []
ingress:
  provider: ""
  options: {}
  node_selector: {}
  extra_args: {}
cluster_name: ""
cloud_provider:
  name: ""
prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
```

**Steps to Reproduce:**
`rke up`

**Results:**
Seems to work okay until it hangs for a few minutes and eventually panics...

```
..INFO[0051] [remove/rke-log-linker] Successfully removed container on host [1]
INFO[0052] [controlplane] Successfully started [rke-log-linker] container on host [2]
INFO[0052] [remove/rke-log-linker] Successfully removed container on host [2]
INFO[0052] [controlplane] Successfully started [kube-scheduler] container on host [1]
INFO[0052] [healthcheck] Start Healthcheck on service [kube-scheduler] on host [1]
INFO[0058] [healthcheck] service [kube-scheduler] on host [1] is healthy
INFO[0058] [controlplane] Successfully started [rke-log-linker] container on host [1]
INFO[0058] [remove/rke-log-linker] Successfully removed container on host [1]
INFO[0311] [controlplane] Successfully started Controller Plane..
INFO[0311] [authz] Creating rke-job-deployer ServiceAccount
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1176346]

goroutine 135 [running]:
github.com/rancher/rke/services.runHealthcheck(0x1dc8000, 0xc4200842d0, 0xc420493700, 0x14eef82, 0xe, 0x0, 0xc4201fcc60, 0x1e, 0x0, 0x0, ...)
        /go/src/github.com/rancher/rke/services/healthcheck.go:72 +0x6a6
github.com/rancher/rke/services.runScheduler(0x1dc8000, 0xc4200842d0, 0xc420493700, 0x0, 0xc420373aa0, 0x14eef82, 0xe, 0xc4201fa200, 0x6, 0x8, ...)
        /go/src/github.com/rancher/rke/services/scheduler.go:16 +0x422
github.com/rancher/rke/services.doDeployControlHost(0x1dc8000, 0xc4200842d0, 0xc420493700, 0x0, 0xc420373aa0, 0xc4203ebf80, 0xc4201834a0, 0x19, 0xc42020b0b0, 0x11bb467, ...)
        /go/src/github.com/rancher/rke/services/controlplane.go:92 +0x3ed
github.com/rancher/rke/services.RunControlPlane.func1(0x8, 0x1577b98)
        /go/src/github.com/rancher/rke/services/controlplane.go:22 +0x11d
github.com/rancher/rke/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc420439bc0, 0xc4200ade00)
        /go/src/github.com/rancher/rke/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
created by github.com/rancher/rke/vendor/golang.org/x/sync/errgroup.(*Group).Go
        /go/src/github.com/rancher/rke/vendor/golang.org/x/sync/errgroup/errgroup.go:66 +0x66
```

Here are the logs from another run:

```
INFO[0068] [healthcheck] Start Healthcheck on service [kube-proxy] on host [2]
INFO[0069] [healthcheck] service [kubelet] on host [3] is healthy
INFO[0070] [worker] Successfully started [rke-log-linker] container on host [3]
INFO[0070] [remove/rke-log-linker] Successfully removed container on host [3]
INFO[0070] [worker] Successfully started [kube-proxy] container on host [3]
INFO[0070] [healthcheck] Start Healthcheck on service [kube-proxy] on host [3]
INFO[0073] [healthcheck] service [kube-proxy] on host [2] is healthy
INFO[0074] [worker] Successfully started [rke-log-linker] container on host [2]
INFO[0074] [remove/rke-log-linker] Successfully removed container on host [2]
INFO[0076] [healthcheck] service [kube-proxy] on host [2] is healthy
INFO[0077] [worker] Successfully started [rke-log-linker] container on host [3]
INFO[0077] [remove/rke-log-linker] Successfully removed container on host [3]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1176346]

goroutine 378 [running]:
github.com/rancher/rke/services.runHealthcheck(0x1dc8000, 0xc4200104b0, 0xc42012f700, 0x14e6692, 0x7, 0x0, 0xc42048fd00, 0x1f, 0xc4204d2540, 0x0, ...)
        /go/src/github.com/rancher/rke/services/healthcheck.go:72 +0x6a6
github.com/rancher/rke/services.runKubelet(0x1dc8000, 0xc4200104b0, 0xc42012f700, 0x0, 0xc4203264e0, 0x14e6692, 0x7, 0xc420576600, 0x1b, 0x20, ...)
        /go/src/github.com/rancher/rke/services/kubelet.go:17 +0x426
github.com/rancher/rke/services.doDeployWorkerPlane(0x1dc8000, 0xc4200104b0, 0xc42012f700, 0x0, 0xc4203264e0, 0xc4202fbbc0, 0xc4204d2540, 0xc4201700c0, 0x19, 0xc420756f88, ...)
        /go/src/github.com/rancher/rke/services/workerplane.go:93 +0x1f3
github.com/rancher/rke/services.RunWorkerPlane.func1(0x8, 0x1577b98)
        /go/src/github.com/rancher/rke/services/workerplane.go:42 +0x76
github.com/rancher/rke/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc420771900, 0xc420732690)
        /go/src/github.com/rancher/rke/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
created by github.com/rancher/rke/vendor/golang.org/x/sync/errgroup.(*Group).Go
        /go/src/github.com/rancher/rke/vendor/golang.org/x/sync/errgroup/errgroup.go:66 +0x66
```

**Comment by galal-hussein** [comment]
@jazoom can you test with v0.1.9 and see if this problem still reproducible, i am not able to reproduce this problem on my side.

**Comment by jazoom** [comment]
Hi @galal-hussein this was a week and a half ago. I just couldn't get RKE not to crash so I moved on and now use kubeadm directly. I had no problems with that.

I can tell you I did try using RKE again with fresh Debian 9 servers a few days after the initial trying, using a different setup (1 master and 3 workers) and the same crash happened.

**Comment by alena1108** [comment]
@galal-hussein can we debug the panic in code? get v0.1.8, locate the line, locate the same line in the latest and see what can be nil at that point

**Comment by jazoom** [comment]
I just spun up a few more Debian 9 nodes to give it a crack with 0.19.0. It hung at the same place as before (after `Successfully removed container on host`) but then the error message was different.

```
INFO[0017] [worker] Successfully started [rke-log-linker] container on host [45.76.113.201]
INFO[0017] [remove/rke-log-linker] Successfully removed container on host [45.76.113.201]
INFO[0017] [healthcheck] service [kube-proxy] on host [149.28.176.159] is healthy
INFO[0017] [worker] Successfully started [rke-log-linker] container on host [45.76.125.156]
INFO[0017] [healthcheck] Start Healthcheck on service [kube-proxy] on host [45.76.113.201]
INFO[0017] [remove/rke-log-linker] Successfully removed container on host [45.76.125.156]
INFO[0018] [worker] Successfully started [rke-log-linker] container on host [149.28.176.159]
INFO[0018] [healthcheck] service [kube-proxy] on host [45.76.113.201] is healthy
INFO[0018] [remove/rke-log-linker] Successfully removed container on host [149.28.176.159]
INFO[0018] [worker] Successfully started [rke-log-linker] container on host [45.76.113.201]
INFO[0019] [remove/rke-log-linker] Successfully removed container on host [45.76.113.201]
FATA[0297] [workerPlane] Failed to bring up Worker Plane: Failed to verify healthcheck for service [kube-proxy]: Failed to get gather logs from container [kube-proxy]: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

Same system config as before, including Docker version.

**Comment by jazoom** [comment]
I just spun up a few more Debian 9 nodes to give it a crack with 0.19.0. It hung at the same place as before (after Successfully removed container on host) but then the error message was different.

```
INFO[0017] [worker] Successfully started [rke-log-linker] container on host [HOST1]
INFO[0017] [remove/rke-log-linker] Successfully removed container on host [HOST1]
INFO[0017] [healthcheck] service [kube-proxy] on host [HOST2] is healthy
INFO[0017] [worker] Successfully started [rke-log-linker] container on host [HOST3]
INFO[0017] [healthcheck] Start Healthcheck on service [kube-proxy] on host [HOST1]
INFO[0017] [remove/rke-log-linker] Successfully removed container on host [HOST3]
INFO[0018] [worker] Successfully started [rke-log-linker] container on host [HOST2]
INFO[0018] [healthcheck] service [kube-proxy] on host [HOST1] is healthy
INFO[0018] [remove/rke-log-linker] Successfully removed container on host [HOST2]
INFO[0018] [worker] Successfully started [rke-log-linker] container on host [HOST1]
INFO[0019] [remove/rke-log-linker] Successfully removed container on host [HOST1]
FATA[0297] [workerPlane] Failed to bring up Worker Plane: Failed to verify healthcheck for service [kube-proxy]: Failed to get gather logs from container [kube-proxy]: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

Same system config as before, including Docker version.

**Comment by jazoom** [comment]
I just tried doing the same again with just one node as controlplane/worker/etcd. Didn't get very far. It's weird, because it's the same setup as all the other times. There shouldn't be anything listening on port 6443.

```
INFO[0000] Building Kubernetes cluster
INFO[0000] [dialer] Setup tunnel for host [HOST]
INFO[0000] [state] Found local kube config file, trying to get state from cluster
INFO[0000] [state] Fetching cluster state from Kubernetes
INFO[0000] [state] Successfully Fetched cluster state to Kubernetes ConfigMap: cluster-state
INFO[0000] [certificates] Getting Cluster certificates from Kubernetes
INFO[0000] [certificates] Successfully fetched Cluster certificates from Kubernetes
INFO[0000] [network] Deploying port listener containers
INFO[0001] [network] Port listener containers deployed successfully
INFO[0001] [network] Running control plane -> etcd port checks
INFO[0001] [network] Successfully started [rke-port-checker] container on host [HOST]
INFO[0001] [network] Running control plane -> worker port checks
INFO[0001] [network] Successfully started [rke-port-checker] container on host [HOST]
INFO[0001] [network] Running workers -> control plane port checks
INFO[0002] [network] Successfully started [rke-port-checker] container on host [HOST]
INFO[0002] [network] Checking KubeAPI port Control Plane hosts
FATA[0023] [network] Can't access KubeAPI port [6443] on Control Plane host: HOST
```

That was after this error:

```
INFO[0000] Building Kubernetes cluster
INFO[0000] [dialer] Setup tunnel for host [HOST]
WARN[0021] Failed to set up SSH tunneling for host [HOST]: Can't retrieve Docker Info: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
WARN[0021] Removing host [HOST] from node lists
FATA[0021] Cluster must have at least one etcd plane host
```

That error message is pretty deceptive. It's asking me if the docker daemon is running, but really, I forgot to change the SSH port to the non-standard port I was using. It wouldn't have even been able to connect to the node at all. I would have realised immediately but I spent a few minutes investigating docker on the node due to that error message. When I fixed that and re-ran `rke up` is when I got the above errors.

**Comment by jazoom** [comment]
I also ran a slightly different server setup routine to my normal, and was able to successfully get a single-node Kubernetes cluster up using RKE. For some reason kubectl proxy wasn't working (I haven't had trouble with kubectl proxy with either of my other non-RKE cluster), but all other functions of kubectl were and the cluster seemed to be in decent shape.

It's late now, but I might have time tomorrow to narrow down exactly which change caused RKE to succeed and I'll try to apply it to a multi-node cluster.

**Comment by jazoom** [comment]
I tried again, this time with a 4-node cluster. It worked, except again the dashboard wasn't accessible via proxy. I remember I had a similar problem where DNS wasn't working when I set up via kubeadm with Flannel, so I tried again with RKE but using Weave. Success. Cluster up and dashboard accessible via `kubectl proxy`. I don't know what's wrong with Flannel, but I couldn't work out last time why DNS wasn't working even with my manual setup.

With Weave, 'hostPort' wasn't working. I guess you don't include the CNI plugin in your setup? I was able to get it working by running this script on each node:

```
rm -rf /tmp/cni-plugins
mkdir /tmp/cni-plugins
cd /tmp/cni-plugins
wget https://github.com/containernetworking/plugins/releases/download/v0.7.1/cni-plugins-amd64-v0.7.1.tgz
tar zxfv cni-plugins-amd64-v0.7.1.tgz
sudo cp /tmp/cni-plugins/portmap /opt/cni/bin/

sudo sh -c 'cat >/etc/cni/net.d/10-mynet.conflist <<-EOF
{
  "cniVersion": "0.3.0",
  "name": "mynet",
    "plugins": [
      {
        "name": "weave",
        "type": "weave-net",
        "hairpinMode": true
      },
      {
        "type": "portmap",
        "capabilities": {"portMappings": true},
        "snat": true
      }
  ]
}
EOF'

rm -f /etc/cni/net.d/10-weave.conf
```

**Comment by jazoom** [comment]
I was also able to investigate why RKE hangs and fails, but I don't think it's related to the panic from before. It hangs when I have firewall rules enabled. I'm not sure why that is, though, since all traffic is allowed over the private network at all ports and 6443 is allowed on the public interface. I thought RKE simply connected to the nodes via SSH and ran the commands from there. What traffic is RKE trying to send to the nodes over other public ports? I haven't tested specifically, but I'm guessing it's either port 80 or port 443 because those are the only other two (along with SSH) that happen to be allowed through the *external* firewall to the worker nodes.

Looking at your [docs here](https://rancher.com/docs/rke/v0.1.x/en/os/) I can only assume that you're testing your ingress service and hanging if it cannot be accessed?

Speaking of which, is there a way *not* to have RKE set up Nginx ingress? I've got this in my `cluster.yml`:

```
ingress:
  provider: ""
  options: {}
  node_selector: {}
  extra_args: {}
```

but RKE still insists on installing an Nginx ingress. I use [Ambassador](https://www.getambassador.io/) for Ingress, so don't think I'd need that.

**Comment by jazoom** [comment]
@galal-hussein as I mentioned I did find "none" in your docs (unless for some reason you don't see my edited response, which would be really weird of GitHub).

I know "certain ports" need to be open. But why do ports 80/443 need to be open? And surely an appropriate warning/error message would be better than just RKE hanging?

**Comment by jazoom** [comment]
And yes, like I mentioned in my previous comments, I did eventually get a cluster up and running. But I am sticking with the kubeadm setup because for some reason the RKE cluster used far more system resources.

**Comment by galal-hussein** [comment]
@jazoom sorry i didnt see the edit part, ports 80/443 are open because of nginx controller which uses these ports, rke hangs because it tries these ports multiple times for a while and you should see a timeout error in port check, however we don't test for 80 or 443 because the user has the option to disable ingress.

Please let me know if you still having any problem with rke.
