### ISSUE TITLE
RKE crash during etcd certs generation

### ISSUE THREAD

**Issue by alexandrem** [rancher/rke#956]
**RKE version:** v0.1.10-rc4

**Steps to Reproduce:**

I don't have the exact steps to reproduce this.

I encountered this last Friday during a k8s cluster disaster recovery procedure.

The overall steps where:
1. provision a fresh cluster with RKE with 3 etcd nodes
2. when done, load a etcd snapshot restore manually to all nodes (without rke etcd restore wrapper)
3. clean some stale etcd data with kube-api (including removing the previous cluster-state file)
4. re-provision with RKE a couple of times
5. possible repeat step 3 and 4, and cleaning up the remote /etc/kubernetes/ folders on control plane nodes to avoid bug #947

**Results:**

```
INFO[0032] [certificates] Regenerating new etcd-10.130.66.35 certificate and key
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2b0 pc=0xa1438a]

goroutine 1 [running]:
github.com/rancher/rke/vendor/github.com/urfave/cli.HandleAction.func1(0xc42058c370)
	/go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/app.go:472 +0x28d
panic(0x13818a0, 0x1e54380)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/rancher/rke/vendor/k8s.io/client-go/util/cert.NewSignedCert(0x15328c9, 0x9, 0x0, 0x0, 0x0, 0xc4200171d0, 0x5, 0x5, 0xc42054ca80, 0x5, ...)
	/go/src/github.com/rancher/rke/vendor/k8s.io/client-go/util/cert/cert.go:106 +0x2ba
github.com/rancher/rke/pki.GenerateSignedCertAndKey(0x0, 0x0, 0x1, 0x15328c9, 0x9, 0xc42030b470, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rke/pki/util.go:47 +0x1a9
github.com/rancher/rke/pki.RegenerateEtcdCertificate(0x1e17d60, 0xc420014880, 0x0, 0xc42048cb00, 0xc42030f940, 0x3, 0x4, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rke/pki/pki.go:222 +0x28b
github.com/rancher/rke/cluster.(*Cluster).GetClusterState(0xc42021e000, 0x1e17d60, 0xc420014880, 0x1534b00, 0x0, 0x0)
	/go/src/github.com/rancher/rke/cluster/state.go:107 +0x6b4
github.com/rancher/rke/cmd.ClusterUp(0x1e17d60, 0xc420014880, 0xc420490000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rke/cmd/up.go:79 +0x191
github.com/rancher/rke/cmd.clusterUpFromCli(0xc4204688c0, 0x0, 0x0)
	/go/src/github.com/rancher/rke/cmd/up.go:195 +0x365
reflect.Value.call(0x131cf60, 0x15c45c0, 0x13, 0x152c5d9, 0x4, 0xc420304310, 0x1, 0x1, 0xc420304298, 0x14f1420, ...)
	/usr/local/go/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0x131cf60, 0x15c45c0, 0x13, 0xc420304310, 0x1, 0x1, 0x140, 0xc4204688c0, 0x0)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/rancher/rke/vendor/github.com/urfave/cli.HandleAction(0x131cf60, 0x15c45c0, 0xc4204688c0, 0x0, 0x0)
	/go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/app.go:481 +0x198
github.com/rancher/rke/vendor/github.com/urfave/cli.Command.Run(0x152c006, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1541af7, 0x14, 0x0, ...)
	/go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/command.go:186 +0xab8
github.com/rancher/rke/vendor/github.com/urfave/cli.(*App).Run(0xc420476000, 0xc420086080, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/rancher/rke/vendor/github.com/urfave/cli/app.go:235 +0x5d6
main.mainErr(0xc420305f78, 0x1213bd8)
	/go/src/github.com/rancher/rke/main.go:52 +0x1982
main.main()
	/go/src/github.com/rancher/rke/main.go:16 +0x22
```

**Comment by deniseschannon** [comment]
@alexandrem if you are sitll facing this issue with v0.2.0, please re-open the issue.
